In [1]:
import numpy as np

# ---------------------------------------------------------
# Task 1: Two friends' daily steps over a week (element-wise ops)
# ---------------------------------------------------------
friend1 = np.array([8000, 9500, 7200, 10000, 8800, 12000, 6500])
friend2 = np.array([7500, 10200, 8000, 9000, 9100, 11000, 7000])

print("Friend 1 steps:", friend1)
print("Friend 2 steps:", friend2)
print("Addition (combined steps):", friend1 + friend2)
print("Subtraction (F1 - F2):    ", friend1 - friend2)
print("Multiplication:           ", friend1 * friend2)
print("Division (F1 / F2):       ", np.round(friend1 / friend2, 2))
print()



Friend 1 steps: [ 8000  9500  7200 10000  8800 12000  6500]
Friend 2 steps: [ 7500 10200  8000  9000  9100 11000  7000]
Addition (combined steps): [15500 19700 15200 19000 17900 23000 13500]
Subtraction (F1 - F2):     [ 500 -700 -800 1000 -300 1000 -500]
Multiplication:            [ 60000000  96900000  57600000  90000000  80080000 132000000  45500000]
Division (F1 / F2):        [1.07 0.93 0.9  1.11 0.97 1.09 0.93]



In [2]:
import numpy as np

user_preferences = np.array([
    [5, 3, 0],
    [4, 0, 2],
    [1, 5, 4],
])
song_popularity = np.array([
    [2, 1, 3],
    [0, 4, 1],
    [5, 2, 0],
])

rec_dot = np.dot(user_preferences, song_popularity)
rec_matmul = np.matmul(user_preferences, song_popularity)

print("Recommendation matrix using np.dot():")
print(rec_dot)
print("Recommendation matrix using np.matmul():")
print(rec_matmul)
print("Are both results equal?", np.array_equal(rec_dot, rec_matmul))

# Difference between dot() and matmul():
# For 2D matrices (like here) both perform standard matrix multiplication and
# give the same result. They differ for other cases:
#  - Scalars: np.dot(2, A) works, but np.matmul does not allow scalar operands.
#  - N-D arrays (3D+): np.matmul treats them as stacks of matrices and
#    multiplies matrix-by-matrix over the last two dimensions (with
#    broadcasting), while np.dot does a sum-product over the last axis of the
#    first array and the second-to-last axis of the second, giving a
#    different, larger output shape.
print()



Recommendation matrix using np.dot():
[[10 17 18]
 [18  8 12]
 [22 29  8]]
Recommendation matrix using np.matmul():
[[10 17 18]
 [18  8 12]
 [22 29  8]]
Are both results equal? True



In [4]:
import numpy as np


image = np.array([
    [ 10,  50, 100, 150],
    [ 20,  60, 110, 160],
    [ 30,  70, 120, 170],
    [ 40,  80, 130, 180],
])

rotated = image.T
print("Original image:")
print(image)
print("Transposed (rotated) image:")
print(rotated)
print("Mean:              ", np.mean(rotated))
print("Median:            ", np.median(rotated))
print("Standard deviation:", np.std(rotated))
print("Variance:          ", np.var(rotated))
print()



Original image:
[[ 10  50 100 150]
 [ 20  60 110 160]
 [ 30  70 120 170]
 [ 40  80 130 180]]
Transposed (rotated) image:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [100 110 120 130]
 [150 160 170 180]]
Mean:               92.5
Median:             90.0
Standard deviation: 53.79358697837503
Variance:           2893.75



In [5]:
import numpy as np


orders = np.array([
    [12, 15, 14, 18, 20, 22],   # City 1 over 6 days
    [10, 13, 16, 17, 19, 21],   # City 2 over 6 days
])
print("Orders (2, 6):")
print(orders)

reshaped = orders.reshape(3, 4)
print("Reshaped to (3, 4):")
print(reshaped)

flat = reshaped.flatten()
print("Flattened:", flat)

part1, part2 = np.split(flat, 2)
print("Part 1:", part1)
print("Part 2:", part2)

stacked = np.vstack((part1, part2))
print("Stacked vertically:")
print(stacked)

Orders (2, 6):
[[12 15 14 18 20 22]
 [10 13 16 17 19 21]]
Reshaped to (3, 4):
[[12 15 14 18]
 [20 22 10 13]
 [16 17 19 21]]
Flattened: [12 15 14 18 20 22 10 13 16 17 19 21]
Part 1: [12 15 14 18 20 22]
Part 2: [10 13 16 17 19 21]
Stacked vertically:
[[12 15 14 18 20 22]
 [10 13 16 17 19 21]]
